// Datos del plan de estudio · Q1 Tardor 2026-27 · GREELEC (ETSETB, UPC)
// Fuentes: guías docentes UPC (230930, 230931, 230922), presentaciones de curso
// de DMIC y HIPS (QT26), calendario de exámenes GREELEC Tardor 26-27 y el
// material de las carpetas de Google Drive.

window.PLAN = (function () {
  const drive = id => "https://drive.google.com/file/d/" + id + "/view";
  const folder = id => "https://drive.google.com/drive/folders/" + id;

  const START = "2026-10-04";      // primer día del plan
  const AFTER_MIDTERMS = "2026-11-12"; // empieza la fase de finales

  const SUBJECTS = {
    DMIC: {
      name: "Disseny Microelectrònic",
      code: "230930",
      course: "4A",
      profs: "Diego Mateo (coord.), Xavier Aragonès; lab: Daniel Marín, Josep Altet",
      folder: folder("1_CjpWQYlMx0JupcHyKm4SeosCVbpXGeG"),
      guide: "https://www.upc.edu/content/grau/guiadocent/pdf/esp/230930",
      evaluation: [
        ["Prácticas (LAB)", "40 %", "Previos y memorias 10 %, Control Lab1 10 %, Control Lab2 10 %, test escrito en el parcial 5 % y en el final 5 %"],
        ["Evaluación continua (AC)", "20 %", "Examen parcial (6/11) y ejercicios para entregar"],
        ["Examen final", "40 %", "7/1/2027. Si te conviene, el final pasa a valer 60 % y la AC 0 %"]
      ],
      syllabus: [
        "Introducción a los circuitos integrados y tecnología CMOS · layout",
        "Transistor MOS: modelos y análisis DC (gran señal)",
        "Circuitos digitales CMOS: característica DC, retardo, consumo, buffers, restricciones temporales",
        "Circuitos analógicos CMOS: pequeña señal, CS / CD / CG / cascode, espejos de corriente, cargas activas, respuesta en frecuencia, etapas diferenciales",
        "RF: LNA de banda estrecha, ruido y no linealidad"
      ]
    },
    HIPS: {
      name: "Sistemes de Hardware de Processament de la Informació",
      code: "230931",
      course: "4A",
      profs: "Jordi Madrenas (coord.), Juan Manuel Moreno",
      folder: folder("1DZlj0AOMDqc8UnqQGE4xk77bB0Rcc35u"),
      extraFolders: [
        ["Labs 2026 (cuenta UPC)", folder("1S03-C4WftLizSpyQSAzb9VPvRs0KAFga")],
        ["Prácticas del curso pasado", folder("1cTfbkZEE3-FMuJB8DxgjYB-L4YbiHRrn")]
      ],
      guide: "https://www.upc.edu/content/grau/guiadocent/pdf/esp/230931",
      evaluation: [
        ["Laboratorio", "40 %", "Asistencia obligatoria para poder ser evaluado"],
        ["Examen parcial", "20 %", "11/11/2026, 14:30–17:00"],
        ["Examen final", "40 %", "15/1/2027, 14:45–17:45. Solo la teoría es reevaluable"]
      ],
      syllabus: [
        "1. Introducción al hardware DSP y de comunicaciones",
        "2. Subsistemas de tratamiento de señal: formatos numéricos, multiplicadores, DDS, CORDIC, filtros FIR/IIR, multirate, CIC, FFT",
        "3. Subsistemas de comunicación: interfaces y protocolos, señalización, codificación, modulaciones",
        "4. Sistemas inteligentes: filtros adaptativos (LMS/RLS) y mecanismos de aprendizaje",
        "Labs 0–8 sobre ZedBoard / Vivado / System Generator"
      ]
    },
    CIAF: {
      name: "Circuits d'Alta Freqüència",
      code: "230922",
      course: "3A",
      profs: "Jordi J. Mallorquí",
      folder: folder("1zWMGXJYqu22yYUGtw6eioacHe4WFiFBs"),
      guide: "https://www.upc.edu/content/grau/guiadocent/pdf/esp/230922",
      evaluation: [
        ["Controles", "15 %", "Parcial del 5/11 y los controles que se anuncien en Atenea"],
        ["Prácticas de ordenador y laboratorio", "25 %", "Obligatorias y no reevaluables"],
        ["Examen final", "60 %", "18/1/2027, 08:00–11:00"]
      ],
      syllabus: [
        "1. Repaso de líneas de transmisión",
        "2. Líneas planares (microstrip, stripline, coplanar…)",
        "3. Carta de Smith y adaptación de impedancias",
        "4. Representación matricial: Z, Y, S, ABCD",
        "5. Circuitos pasivos: atenuadores, filtros, divisores, Wilkinson, circuladores, híbridos, acopladores",
        "6. Circuitos activos: ruido y Friis, detectores y mezcladores, amplificadores, osciladores",
        "7. Circuitos híbridos y monolíticos (MMIC)",
        "8. CAD: QUCS",
        "9. Instrumentos: analizador de espectro, VNA, medidor de figura de ruido"
      ]
    }
  };

  const EXAMS = [
    { subj: "CIAF", kind: "P", date: "2026-11-05", time: "11:00–13:30", label: "Parcial CIAF", weight: "Cuenta en controles (15 %)" },
    { subj: "DMIC", kind: "P", date: "2026-11-06", time: "11:00–13:30", label: "Parcial DMIC", weight: "AC 20 % + test de lab 5 %" },
    { subj: "HIPS", kind: "P", date: "2026-11-11", time: "14:30–17:00", label: "Parcial HIPS", weight: "20 %" },
    { subj: "DMIC", kind: "F", date: "2027-01-07", time: "14:45–17:45", label: "Final DMIC", weight: "40 % + test de lab 5 %" },
    { subj: "HIPS", kind: "F", date: "2027-01-15", time: "14:45–17:45", label: "Final HIPS", weight: "40 %" },
    { subj: "CIAF", kind: "F", date: "2027-01-18", time: "08:00–11:00", label: "Final CIAF", weight: "60 %" }
  ];

  const MILESTONES = [
    { date: "2026-10-07", label: "Diada Campus Nord: sin laboratorios, teoría solo de 8 a 11 h" },
    { date: "2026-11-05", label: "Semana de parciales: del 5 al 11/11 no hay clase" },
    { date: "2026-12-23", label: "Último día de clase" },
    { date: "2027-01-27", label: "Fecha límite de notas definitivas" }
  ];

  // Días sin estudio por defecto (se pueden cambiar en Ajustes → días libres)
  const HOLIDAYS = ["2026-12-24", "2026-12-25", "2026-12-31", "2027-01-01"];

  // Archivos de Drive referenciados por las tareas
  const FILES = {
    // DMIC
    dPres: ["Presentació QT26", drive("1x67il3NRlM2kRk0DiziqlGy71pQztnyg")],
    dTec: ["Technologia v3", drive("1PloE_2wQyasA1T4Fx9KTFzwz1Z9D7-dt")],
    dMosEq: ["MOS Equations v4", drive("19mhPuFuoenNkwXQmTsU6fwqf8btjPNFj")],
    dCap: ["capacitats v2", drive("1STAP_aB37XMMX3LEOowcL6dqD6qMi7Sp")],
    dInvPmos: ["Inversor PMOS (sol)", drive("1OK-_2fE5u7TRPeJLcdvYeVWp03bwj0lC")],
    dInvx2: ["Invx2", drive("1eLujI0TMPFC4XB2a5NOGWlX13JCXehM9")],
    dTasca2: ["Tasca 2 Inversors (sol)", drive("1Gi7pLp7em8ZdiRU3GCLMNwxwVyqMf9bu")],
    dTask2mine: ["Tu Task 2 entregada", drive("1WmOl7eCtTomMo9NgAf5A7nBvsV15hjux")],
    dCSCD: ["Exercici classe CS-CD", drive("1hjQdm83qyo9OPHpwG8DoIimR1np863-i")],
    dExAn: ["Exercises Analog", drive("1zAAG9js3o2b_efUiAtt4gpPnqOEvVhBu")],
    dExRF: ["Exercises RF", drive("1z1c6UKkDaO2EG5Vkr0mhOfMg_JsSiOp6")],
    dDD4: ["Disseny Digital T4 (repaso)", drive("19N51H_b1T03mTNqNzuuiO9Cygx4ncTvT")],
    dL1: ["Lab1 Tutorial Q24T", drive("10AF3Ys8Dv3b25sMj3VAyA7PRfeL-qyg4")],
    dL2: ["Lab2 Digital Q25T", drive("1wi_Tdj8oQsF8vlqNLd-YCYEfLBGnABnv")],
    dL3a: ["Lab3a Analog Q24P", drive("1WfG7O8Xk0_a5kWyA88MKiJzNMeNgRQem")],
    dL3b: ["Lab3b Analog Q25T", drive("1KMOktdIxZbwm8tLNdupU0MmpPDQrWba5")],
    dL4: ["Lab4 RF Q24T", drive("1yhkQJHM_r4OSppmX515i5rHjZm5kQRMy")],
    dExF23: ["Final QT23 (sol)", drive("12FEt_8oPTCiJ2Vo4TTfLIh6kLRewnvml")],
    dExF24: ["Final 24-25 Tardor (sol)", drive("1vfHshtpfk6-NZXINTMQd1e7pSNI2s0f_")],
    dExP1_25: ["Final P1 QT25 (sol)", drive("1rEn4_JqrL8BjM3wUmiK9Tq54d5nO2egO")],
    dLabEx23: ["Examen Lab QT23", drive("196uB38NJwnimaR-Mq9CftIuTfDMkR5g6")],
    dLabF24: ["Final Lab QT24", drive("1mlqWHsuHyGPUowfY7Bt3blGruvhkwMj2")],
    dLabF25: ["Final Lab QT25 (sol)", drive("1HilQj4YOdcj-rPRZ91GZHD3ZjW3LAmPH")],
    dChul: ["Tu chuleta final", drive("10QY3xf_qVQ64KDhiTXc9Rk3caPNxd0Ff")],
    dForm: ["Tu formulario completo", drive("1VLHWvVSb1OcJFchODDEL5htQ-LPFQ6m-")],
    // HIPS
    hOrg: ["Course Organization 2026", drive("1Uk9g5bbABrrTPKgmd6D0uqAOOGmI2f6U")],
    hC1: ["Chapter 1 Introduction", drive("1r4oOAQUJgi0v9QW8gUz_9H_fZ8BGwvDk")],
    hC2a: ["Chapter 2 · parte 1", drive("14RiHaqlmmecxjF1BJlH1wvdpNm9U5o2q")],
    hC2b: ["Chapter 2 · parte 2", drive("1jTeaNjBUlqJuJMlKb1t537s-KdQgFYkN")],
    hC2c: ["Chapter 2 · parte 3", drive("1mgYoyBSIuHUEeex6TIETXBSkGnjSCVv1")],
    hC3: ["Chapter 3 Communication", drive("1RxFKtJ941mwydKebM9JsoN6ykvs0fFAt")],
    hEx2: ["Exercises Chapter 2", drive("1nsPy-lOFRPfQRQxo13Rg3Zw09mrS3DN8")],
    hEx3: ["Exercises Chapter 3", drive("11WTU4XktG8pJyr2Ae5nWLL_AbOwDCjwQ")],
    hEx3mine: ["Tus ejercicios Tema 3", drive("1pKV2leZCeYK73mafEXLAfLi6tV2hgtyM")],
    hCtl25: ["Control 25 T (sol)", drive("18qRlWcvMbzmkGwnzEqSwvk9SWeRXgq98")],
    hF21: ["Final 2021-22 (sol)", drive("1LODe1yHbyEVsfpl2SiFnlK5u4BxjLhEz")],
    hF22: ["Final 2022-23 (sol)", drive("1v5EZqEt3Rrc_8oNmG9cda2dzRBHOaTeY")],
    hF24: ["Final 2024 fall (sol)", drive("1haqkDFqoMlM3PbyJ4Y11nllDR8BRvlSq")],
    hF25: ["Examen 25 T (sol)", drive("1aCSK6lOzrIZAigwOG3pQSQZy5ya2ZaN9")],
    hR22: ["Reavaluació 2022-23 (sol)", drive("19I7hpIFbN6B4lkdqq0FR4lv1i5e4hpbn")],
    hLabs: ["Carpeta Labs 2026", folder("1S03-C4WftLizSpyQSAzb9VPvRs0KAFga")],
    hPrev: ["Prácticas curso pasado", folder("1cTfbkZEE3-FMuJB8DxgjYB-L4YbiHRrn")],
    // CIAF
    cLT: ["Líneas de Transmisión v10", drive("1FrVc-W2atYBva3nYvTqkqwaAv7EydoQf")],
    cPlanar: ["Planar lines v2", drive("1I7gpNNvZ5BkJ2BZKz2lSquSEIEg-PZOC")],
    cConn: ["RF connectors", drive("1TDF30EvUuoLurnuNJA2NIOgiIHvgkViC")],
    cMsQ: ["Microstrip en QUCS", drive("1im50dUEpQXShUAM5fdl76wXsYqVuOjFM")],
    cP1: ["Problemas T1 (1_LT_d)", drive("101IwlSIHeK15Yd_MN5VR4HNf6MiSMq9f")],
    cP1sol: ["Soluciones T1", drive("1zYfJdIP4T3rlqOjGPbsPH9Q67Gz1UiQa")],
    cEjLC: ["Ejemplos líneas y cargas", drive("1NfIY4UhP6XorkhlY5WOmCK7HVcplnQwL")],
    cPot: ["potencia2", drive("1mkv7SGKSyY_wgXlGMEhv8BNicpXfJGqB")],
    cSmith: ["Smith Chart v1", drive("1Tx23f63x16VaLfGw1H6YLYeP0PYZ-66-")],
    cT2e: ["Enunciados carta de Smith", drive("1R3vdjkSzjAmBYtk_9jMvcjw2PCN-N_Oq")],
    cT2s: ["Soluciones carta de Smith", drive("1I6vVVqhjPe-PATJxiZI3mEIvgdCP5j0m")],
    cT2zip: ["Ejercicios transparencias (zip)", drive("1UibSuzw2sO-TRoJ6MjyCEe_wmAEeH7Pq")],
    cCartas: ["Cartas de Smith en blanco (zip)", drive("1yADYvpic02pJzfbVbGDStgDC8ESfhcqV")],
    cS: ["S Parameters v5", drive("1tYxIuMUQLu6Ej4MobbrvJk0j_r-7WXwf")],
    cAcop: ["Líneas acopladas", drive("1e6bQ6MzC314x7d1y8w-V3nXqoZ1jebm9")],
    cQucs: ["QUCS circuits v3", drive("1ibhseFaG76U_tTVrcEo6X7_tVR4frp8V")],
    cT3e: ["Enunciados parámetros S", drive("1thRhwA_Na-rKnU7GzgaeJO1jk5cSgs3h")],
    cT3s: ["Soluciones parámetros S", drive("1UjwVpyEocXQXq72sRVj_uAqviVyg7Ekt")],
    cAmp: ["MW amplifiers v2", drive("1748mcva3yD2UKdokSFYefwOR2kvE0wm3")],
    cT4t: ["Teoría amplificadores", drive("1NKocaMu4Oq1RwQ-rDx1jHoGnBa4HAbVa")],
    cT4e: ["Enunciados amplificadores", drive("1OtpenYjf2t62ra2RVfHVeaL3Xnu89fE4")],
    cT4s: ["Amplificadores resueltos", drive("1PuDmC9XZjApcEg4puxxHj9CPHQ5k1S-k")],
    cOsc: ["Problemas osciladores", drive("1cTjASjoGX1m5KTixE12yfd2-TlVspPL8")],
    cEx24: ["Examen CIAF 18/01/24", drive("1W74g46uOQZuWJa_Au8OEJ-jQWssHY34l")],
    cEx24s: ["Examen CIAF 18/01/24 (sol)", drive("159PlqLkZwinS-fBkmI7MJfW8VzQv3v3o")],
    cM17: ["MICROS 2017-18 final", drive("1pZ_x9-Bd6aNM3DeGIWPqYGimOsDQ9L45")],
    cM16: ["MICROS 2016-17 final", drive("1g-bDDGTI9hmJk1PQ99o6zv_iIcy5SkRm")],
    cForm: ["Formulario", drive("1MQlcQ6l6QQCo_Z2T4kkYnt9IS4uyL6nA")]
  };

  // ph: "P" = hasta el parcial, "F" = hasta el final. m = minutos.
  // due: fecha límite propia (si la tarea vence antes que el examen).
  const TASKS = [
    // ───────────── DMIC · parcial 6/11 ─────────────
    { id: "dmic-p01", s: "DMIC", ph: "P", m: 60, t: "Presentación y tecnología CMOS",
      f: ["dPres", "dTec"],
      steps: ["Lee la presentación QT26: calendario, labs y cómo se evalúa.",
              "Lee Technologia v3: por qué CMOS, nodos tecnológicos y pasos de fabricación.",
              "Resumen en papel: el proceso de fabricación en 6–8 pasos con un dibujo de la sección de un inversor CMOS."] },
    { id: "dmic-p02", s: "DMIC", ph: "P", m: 75, t: "Layout CMOS y Lab1 (secciones T1–T4)",
      f: ["dTec", "dL1"],
      steps: ["Repasa las capas (pozo, difusión, poly, contactos, metal) y la idea de reglas de diseño (λ).",
              "Lee las secciones T1–T4 del guion del Lab1, como pide el profesor antes de la sesión.",
              "Resumen: dibuja a mano el layout de un inversor y marca cada capa."] },
    { id: "dmic-p03", s: "DMIC", ph: "P", m: 75, t: "Transistor MOS: ecuaciones y regiones",
      f: ["dMosEq", "dForm"],
      steps: ["Estudia MOS Equations v4: corte, triodo y saturación; modulación de canal (λ) y efecto cuerpo.",
              "Resumen: ficha de una cara con las ecuaciones NMOS/PMOS y las condiciones de cada región.",
              "Comprueba que sabes deducir VDSsat y la curva ID(VDS)."] },
    { id: "dmic-p04", s: "DMIC", ph: "P", m: 90, t: "Análisis DC de circuitos MOS (gran señal)",
      f: ["dInvPmos", "dMosEq"],
      steps: ["Polarización por tensión y por corriente: método «supongo región → calculo → verifico».",
              "Haz el ejercicio del inversor PMOS sin mirar la solución y corrígelo después.",
              "Resumen: el método paso a paso en una ficha. Si las transparencias del tema no están en tu Drive, descárgalas de Atenea (ver Material)."] },
    { id: "dmic-p05", s: "DMIC", ph: "P", m: 60, t: "Capacidades del MOS",
      f: ["dCap"],
      steps: ["Capacidades de puerta (Cgs, Cgd, Cgb) por región y capacidades de unión.",
              "Resumen: tabla de capacidades por región y la capacidad de carga de una puerta."] },
    { id: "dmic-p06", s: "DMIC", ph: "P", m: 75, t: "Puertas CMOS: característica DC del inversor",
      f: ["dInvx2"],
      steps: ["VTC del inversor: VM, VIL, VIH, márgenes de ruido y cómo influye el ratio Wp/Wn.",
              "Trabaja el ejercicio Invx2.",
              "Resumen: VTC dibujada con las regiones de cada transistor tramo a tramo."] },
    { id: "dmic-p07", s: "DMIC", ph: "P", m: 90, t: "Retardo de propagación",
      f: ["dTasca2", "dTask2mine"],
      steps: ["Modelo RC del transistor, tPHL / tPLH y su dependencia con la carga y el dimensionado.",
              "Rehaz la Tasca 2 (dos inversores) sin mirar y compara con la solución y con tu entrega.",
              "Resumen: fórmulas de retardo y un ejemplo numérico."] },
    { id: "dmic-p08", s: "DMIC", ph: "P", m: 60, t: "Consumo estático y dinámico",
      f: [],
      steps: ["P = α·C·VDD²·f, corriente de cortocircuito y fugas.",
              "Resumen: tabla de los tipos de consumo y de qué depende cada uno.",
              "Haz los apartados de consumo de los exámenes finales de DMIC."] },
    { id: "dmic-p09", s: "DMIC", ph: "P", m: 75, t: "Buffers escalados",
      f: [],
      steps: ["Cadena de inversores: factor de escala óptimo (≈ e…4), número de etapas y retardo total.",
              "Resumen: deducción del número óptimo de etapas y un ejemplo resuelto.",
              "Busca un ejercicio de buffers en los finales QT23 o 24-25 y hazlo."] },
    { id: "dmic-p10", s: "DMIC", ph: "P", m: 45, t: "Restricciones temporales (setup / hold)",
      f: ["dDD4"],
      steps: ["Repasa el apartado 4.3 «Temporització de circuits síncrons» de Disseny Digital T4.",
              "Resumen: condición de setup y de hold con el retardo de puertas CMOS."] },
    { id: "dmic-p11", s: "DMIC", ph: "P", m: 60, t: "Lab2 digital: previo",
      f: ["dL2"],
      steps: ["Prepara el estudio previo del Lab2 (diseño y análisis de puertas digitales).",
              "Anota las dudas para la sesión de laboratorio."] },
    { id: "dmic-p12", s: "DMIC", ph: "P", m: 90, t: "Pequeña señal y etapa de surtidor común",
      f: ["dCSCD", "dExAn"],
      steps: ["Modelo de pequeña señal: gm, ro y gmb.",
              "Etapa CS con carga resistiva: ganancia, Rin y Rout.",
              "Haz el ejercicio de clase CS-CD. Resumen: modelo y ganancia de la CS en una ficha."] },
    { id: "dmic-p13", s: "DMIC", ph: "P", m: 90, t: "Examen: Final P1 QT25 (parte digital)",
      f: ["dExP1_25"],
      steps: ["Hazlo sin mirar la solución y con el tiempo limitado.",
              "Corrige con la solución y anota en tu resumen cada error."] },
    { id: "dmic-p14", s: "DMIC", ph: "P", m: 75, t: "Examen: Final QT23 (problemas digitales)",
      f: ["dExF23"],
      steps: ["Haz solo los problemas de MOS DC y digital.",
              "Corrige y añade a la ficha las fórmulas que te faltaban."] },
    { id: "dmic-p15", s: "DMIC", ph: "P", m: 60, t: "Ficha de fórmulas para el parcial",
      f: ["dForm", "dChul"],
      steps: ["Parte de tu formulario y tu chuleta y quédate solo con lo que entra en el parcial.",
              "Haz una ficha en limpio en papel."] },
    { id: "dmic-p16", s: "DMIC", ph: "P", m: 150, t: "Simulacro de parcial (2 h 30 min)",
      f: ["dExF24"],
      steps: ["Haz la parte digital y MOS del final 24-25 en 2 h 30 min, como en el parcial real.",
              "Corrige y repasa lo que falló."] },
    { id: "dmic-p17", s: "DMIC", ph: "P", m: 60, t: "Test de laboratorio (5 % en el parcial)",
      f: ["dLabEx23", "dLabF24", "dL1"],
      steps: ["Repasa Lab1 (Virtuoso, layout, curvas del MOS) con el examen de lab QT23 y el final de lab QT24.",
              "Resumen: lista de preguntas tipo test con respuesta."] },

    // ───────────── DMIC · final 7/1 ─────────────
    { id: "dmic-f01", s: "DMIC", ph: "F", m: 75, t: "Preparar Control Lab1", due: "2026-11-16",
      f: ["dLabF25", "dL1", "dL2"],
      steps: ["Confirma en Atenea la fecha según tu grupo de lab. Si tu control es la semana del 9/11, adelanta esta tarea.",
              "Repasa Lab1 y Lab2 y haz la parte correspondiente del Final Lab QT25."] },
    { id: "dmic-f02", s: "DMIC", ph: "F", m: 90, t: "Surtidor común con carga activa",
      f: ["dExAn"],
      steps: ["Ganancia, impedancias y excursión de salida.",
              "Haz los primeros ejercicios de Exercises Analog.",
              "Resumen: tabla de etapas (Av, Rin, Rout) que irás completando."] },
    { id: "dmic-f03", s: "DMIC", ph: "F", m: 90, t: "Drenador común, puerta común y cascode",
      f: ["dCSCD", "dExAn"],
      steps: ["Seguidor de surtidor, etapa de puerta común y estructura cascode.",
              "Completa la tabla de etapas.",
              "Haz los ejercicios de Exercises Analog sobre estas etapas."] },
    { id: "dmic-f04", s: "DMIC", ph: "F", m: 75, t: "Fuentes y espejos de corriente",
      f: ["dExAn"],
      steps: ["Espejo simple y cascode: relación de copia, Rout y errores por λ.",
              "Resumen: esquema y fórmulas de cada espejo."] },
    { id: "dmic-f05", s: "DMIC", ph: "F", m: 60, t: "Cargas activas",
      f: ["dExAn"],
      steps: ["CS con carga activa (espejo PMOS): ganancia intrínseca gm·ro.",
              "Haz un ejercicio de examen sobre cargas activas."] },
    { id: "dmic-f06", s: "DMIC", ph: "F", m: 90, t: "Respuesta en frecuencia de amplificadores",
      f: ["dExAn"],
      steps: ["Efecto Miller, polos dominantes y ancho de banda de las etapas CS, CD y CG.",
              "Resumen: método para estimar polos y un ejemplo."] },
    { id: "dmic-f07", s: "DMIC", ph: "F", m: 75, t: "Par diferencial con carga resistiva",
      f: ["dExAn"],
      steps: ["Definiciones de modo diferencial y común; ganancias y salida totalmente diferencial.",
              "Resumen y un ejercicio."] },
    { id: "dmic-f08", s: "DMIC", ph: "F", m: 75, t: "Par diferencial con carga espejo",
      f: ["dExAn"],
      steps: ["Salida single-ended, ganancia y CMRR.",
              "Haz el ejercicio de etapas diferenciales de un examen final."] },
    { id: "dmic-f09", s: "DMIC", ph: "F", m: 60, t: "Lab3 analógico: previos",
      f: ["dL3a", "dL3b"],
      steps: ["Prepara los previos del Lab3 (single-ended y diferencial)."] },
    { id: "dmic-f10", s: "DMIC", ph: "F", m: 75, t: "Preparar Control Lab2", due: "2026-12-10",
      f: ["dLabF24", "dLabF25", "dL3b"],
      steps: ["Confirma la fecha en Atenea (semana del 10 o 17/12 según tu grupo).",
              "Haz la parte analógica de los finales de lab QT24 y QT25."] },
    { id: "dmic-f11", s: "DMIC", ph: "F", m: 75, t: "Ruido en circuitos",
      f: ["dExRF"],
      steps: ["Fuentes de ruido del MOS, densidad espectral y figura de ruido (NF).",
              "Resumen: fórmulas de NF y del ruido referido a la entrada."] },
    { id: "dmic-f12", s: "DMIC", ph: "F", m: 60, t: "No linealidad",
      f: ["dExRF"],
      steps: ["Compresión a 1 dB, intermodulación e IP3.",
              "Resumen y un ejercicio de Exercises RF."] },
    { id: "dmic-f13", s: "DMIC", ph: "F", m: 90, t: "Cabezales RF y LNA de banda estrecha",
      f: ["dExRF", "dL4"],
      steps: ["Estructura del receptor, LNA con degeneración inductiva y adaptación de entrada.",
              "Mira el guion del Lab RF Q24T como apoyo.",
              "Resumen: esquema del LNA y sus ecuaciones."] },
    { id: "dmic-f14", s: "DMIC", ph: "F", m: 75, t: "Ejercicios RF",
      f: ["dExRF"],
      steps: ["Haz el resto de Exercises RF sin mirar las soluciones."] },
    { id: "dmic-f15", s: "DMIC", ph: "F", m: 75, t: "Repaso de la parte digital",
      f: ["dExF23", "dExF24"],
      steps: ["Rehaz 3 problemas digitales que fallaste en el parcial o en los simulacros."] },
    { id: "dmic-f16", s: "DMIC", ph: "F", m: 210, t: "Simulacro: Final 24-25 completo (3 h)",
      f: ["dExF24"],
      steps: ["Hazlo entero en 3 h y luego corrígelo (30 min)."] },
    { id: "dmic-f17", s: "DMIC", ph: "F", m: 180, t: "Simulacro: Final QT23 completo",
      f: ["dExF23"],
      steps: ["Hazlo entero cronometrado y corrígelo."] },
    { id: "dmic-f18", s: "DMIC", ph: "F", m: 90, t: "Final P1 QT25 y formulario final",
      f: ["dExP1_25", "dForm"],
      steps: ["Rehaz los problemas que no te salieron.",
              "Pasa a limpio el formulario final."] },
    { id: "dmic-f19", s: "DMIC", ph: "F", m: 60, t: "Test de laboratorio del final (5 %)",
      f: ["dLabEx23", "dLabF25"],
      steps: ["Repasa las preguntas tipo test de los tres labs."] },
    { id: "dmic-f20", s: "DMIC", ph: "F", m: 60, t: "Repaso general",
      f: ["dChul"],
      steps: ["Lee tus fichas y tu lista de errores típicos. Nada nuevo."] },

    // ───────────── HIPS · parcial 11/11 ─────────────
    { id: "hips-p01", s: "HIPS", ph: "P", m: 90, t: "Organización y Chapter 1: Introducción",
      f: ["hOrg", "hC1"],
      steps: ["Lee la organización del curso (fechas y labs).",
              "Chapter 1: consumo, velocidad, área; muestreo y cuantificación; sample rate vs throughput vs reloj.",
              "Resumen: mapa conceptual del capítulo."] },
    { id: "hips-p02", s: "HIPS", ph: "P", m: 60, t: "Concurrencia, pipelining y retiming",
      f: ["hC1"],
      steps: ["Paralelismo, interleaving, pipelining y retiming, más el procesado multirate básico.",
              "Resumen: un ejemplo de pipelining de un FIR con su ruta crítica antes y después."] },
    { id: "hips-p03", s: "HIPS", ph: "P", m: 90, t: "Precisión y formatos numéricos",
      f: ["hC2a"],
      steps: ["Saturación, truncado y redondeo; punto fijo y punto flotante; rango dinámico; IEEE 754.",
              "Resumen: tabla de formatos con su rango y resolución, y la codificación IEEE 754."] },
    { id: "hips-p04", s: "HIPS", ph: "P", m: 90, t: "Multiplicadores y bloques DSP",
      f: ["hC2a"],
      steps: ["Multiplicador paralelo-paralelo, Robertson, radix-4 (Booth) y serie-paralelo.",
              "Bloques DSP y de memoria de la FPGA, procesado por bloques y aritmética compleja.",
              "Resumen: comparativa de multiplicadores (área / ciclos)."] },
    { id: "hips-p05", s: "HIPS", ph: "P", m: 75, t: "Ejercicios del Chapter 2 (formatos y multiplicadores)",
      f: ["hEx2"],
      steps: ["Haz los ejercicios de formatos y multiplicadores sin mirar las soluciones."] },
    { id: "hips-p06", s: "HIPS", ph: "P", m: 60, t: "DDS: síntesis digital directa",
      f: ["hC2b"],
      steps: ["Acumulador de fase, tabla y resolución en frecuencia.",
              "Resumen: diagrama de bloques y fórmula de fout."] },
    { id: "hips-p07", s: "HIPS", ph: "P", m: 90, t: "Algoritmo CORDIC",
      f: ["hC2b", "hEx2"],
      steps: ["Modos rotación y vectorización, ganancia K, iteraciones e implementación en hardware.",
              "Haz a mano 3–4 iteraciones de un ejemplo.",
              "Resumen: ecuaciones de iteración y su arquitectura."] },
    { id: "hips-p08", s: "HIPS", ph: "P", m: 90, t: "Filtros FIR e IIR en hardware",
      f: ["hC2b", "hC2c"],
      steps: ["FIR en forma directa y transpuesta y aprovechamiento de la simetría.",
              "IIR: estabilidad, transformada bilineal y secciones de segundo orden (SOS); compromiso entre selectividad y coste.",
              "Resumen: estructuras dibujadas con su número de multiplicadores."] },
    { id: "hips-p09", s: "HIPS", ph: "P", m: 90, t: "Multirate, polifase y CIC",
      f: ["hC2c"],
      steps: ["Decimación e interpolación, filtros polifásicos y CIC (media móvil, compensación).",
              "Resumen: respuesta del CIC y crecimiento de bits."] },
    { id: "hips-p10", s: "HIPS", ph: "P", m: 60, t: "DFT y FFT",
      f: ["hC2c"],
      steps: ["FFT radix-2, mariposas, número de operaciones y uso de IP cores.",
              "Resumen: diagrama de una FFT de 8 puntos."] },
    { id: "hips-p11", s: "HIPS", ph: "P", m: 60, t: "Labs: diseño síncrono y conversión D/A",
      f: ["hLabs", "hPrev"],
      steps: ["Prepara Lab 2 y Lab 3 apoyándote en tus prácticas del curso pasado.",
              "Repasa VHDL: contadores, registros de desplazamiento y FSM."] },
    { id: "hips-p12", s: "HIPS", ph: "P", m: 150, t: "Simulacro: Control 25 T",
      f: ["hCtl25"],
      steps: ["Es el parcial del curso pasado: hazlo en 2 h 30 min sin solución.",
              "Corrige y anota los errores."] },
    { id: "hips-p13", s: "HIPS", ph: "P", m: 90, t: "Preguntas del Chapter 1–2 en finales anteriores",
      f: ["hF24", "hF25"],
      steps: ["Haz solo las preguntas de los capítulos 1 y 2 de los finales de 2024 y 2025."] },
    { id: "hips-p14", s: "HIPS", ph: "P", m: 60, t: "Ficha de resumen para el parcial",
      f: [],
      steps: ["Una o dos caras con fórmulas y arquitecturas clave del Chapter 1–2."] },
    { id: "hips-p15", s: "HIPS", ph: "P", m: 60, t: "Rehacer los ejercicios fallados",
      f: ["hEx2", "hCtl25"],
      steps: ["Vuelve a hacer lo que falló en el simulacro y en los ejercicios."] },

    // ───────────── HIPS · final 15/1 ─────────────
    { id: "hips-f01", s: "HIPS", ph: "F", m: 90, t: "Interfaces y protocolos",
      f: ["hC3"],
      steps: ["On-chip vs off-chip, paralelo vs serie y con o sin reloj.",
              "SPI, I2C/I3C, USB, CAN, FlexRay, AXI, PCIe, MIPI y JESD204.",
              "Resumen: tabla comparativa de protocolos."] },
    { id: "hips-f02", s: "HIPS", ph: "F", m: 90, t: "Señalización en banda base",
      f: ["hC3"],
      steps: ["ISI, códigos de línea (RZ / NRZ), pulsos de Nyquist y gaussianos, 8b/10b y 64b/66b.",
              "Filtro adaptado, sincronización y CDR.",
              "Resumen: esquemas y fórmulas clave."] },
    { id: "hips-f03", s: "HIPS", ph: "F", m: 75, t: "Ejercicios del Chapter 3 (parte 1)",
      f: ["hEx3", "hEx3mine"],
      steps: ["Ejercicios de interfaces y señalización. Compáralos con los que hiciste el curso pasado."] },
    { id: "hips-f04", s: "HIPS", ph: "F", m: 60, t: "Codificación de fuente",
      f: ["hC3"],
      steps: ["Huffman y Lempel-Ziv: haz un ejemplo de cada uno a mano."] },
    { id: "hips-f05", s: "HIPS", ph: "F", m: 90, t: "Codificación de canal (FEC)",
      f: ["hC3"],
      steps: ["Scrambling e interleaving, CRC, Reed-Solomon, convolucionales y Viterbi, turbo y LDPC.",
              "Resumen: cálculo de un CRC y un trellis de Viterbi a mano."] },
    { id: "hips-f06", s: "HIPS", ph: "F", m: 90, t: "Modulaciones digitales",
      f: ["hC3"],
      steps: ["PAM, ASK/FSK/PSK, QAM, GMSK, QPSK (π/4 y offset), CDMA y COFDM.",
              "Resumen: constelaciones e implementación en hardware de un modulador I/Q."] },
    { id: "hips-f07", s: "HIPS", ph: "F", m: 75, t: "Ejercicios del Chapter 3 (parte 2)",
      f: ["hEx3", "hEx3mine"],
      steps: ["Ejercicios de codificación y modulación."] },
    { id: "hips-f08", s: "HIPS", ph: "F", m: 75, t: "Filtros adaptativos: LMS y RLS",
      f: [],
      steps: ["Necesitas las transparencias del Chapter 4 de Atenea (no están en tu Drive).",
              "Identificación de sistemas, cancelación de ruido y predicción; LMS y RLS con QR.",
              "Resumen: ecuaciones de actualización y arquitectura."] },
    { id: "hips-f09", s: "HIPS", ph: "F", m: 75, t: "Mecanismos de aprendizaje",
      f: [],
      steps: ["Chapter 4.2 (de Atenea): tipos de redes neuronales; MLP, KNN, SVM, RBF y SOM; CNN; herramientas en lógica programable.",
              "Resumen: tabla de modelos con su coste en hardware."] },
    { id: "hips-f10", s: "HIPS", ph: "F", m: 60, t: "Labs 4–8: A/D, System Generator, filtros, CIC y FFT",
      f: ["hLabs", "hPrev"],
      steps: ["Prepara las sesiones que quedan y anota qué conceptos de teoría usa cada lab."] },
    { id: "hips-f11", s: "HIPS", ph: "F", m: 180, t: "Simulacro: Final 2021-22",
      f: ["hF21"],
      steps: ["Hazlo cronometrado (3 h) y corrígelo."] },
    { id: "hips-f12", s: "HIPS", ph: "F", m: 180, t: "Simulacro: Final 2022-23",
      f: ["hF22"],
      steps: ["Hazlo cronometrado (3 h) y corrígelo."] },
    { id: "hips-f13", s: "HIPS", ph: "F", m: 180, t: "Simulacro: Final 2024 fall",
      f: ["hF24"],
      steps: ["Hazlo cronometrado (3 h) y corrígelo."] },
    { id: "hips-f14", s: "HIPS", ph: "F", m: 180, t: "Simulacro: Examen 25 T",
      f: ["hF25"],
      steps: ["Es el examen más reciente: hazlo el último y en condiciones reales."] },
    { id: "hips-f15", s: "HIPS", ph: "F", m: 120, t: "Reavaluació 2022-23",
      f: ["hR22"],
      steps: ["Haz las preguntas de los temas en los que vas más flojo."] },
    { id: "hips-f16", s: "HIPS", ph: "F", m: 75, t: "Ficha final y repaso",
      f: [],
      steps: ["Une las fichas de los cuatro capítulos y repasa tu lista de errores."] },

    // ───────────── CIAF · parcial 5/11 ─────────────
    { id: "ciaf-p01", s: "CIAF", ph: "P", m: 90, t: "Líneas de transmisión: teoría",
      f: ["cLT"],
      steps: ["Ecuaciones del telegrafista, γ y Z0, coeficiente de reflexión, ROE y potencia; líneas con pérdidas.",
              "Resumen: fórmulas de Zin(l) y Γ(l) y el caso de generador y carga desadaptados."] },
    { id: "ciaf-p02", s: "CIAF", ph: "P", m: 90, t: "Problemas de líneas de transmisión",
      f: ["cP1", "cP1sol", "cEjLC", "cPot"],
      steps: ["Haz los problemas del tema 1 sin mirar las soluciones.",
              "Repasa los ejemplos de líneas y cargas y el documento de potencia."] },
    { id: "ciaf-p03", s: "CIAF", ph: "P", m: 75, t: "Líneas planares",
      f: ["cPlanar", "cMsQ", "cConn"],
      steps: ["Modos TEM y cuasi-TEM; microstrip, stripline y coplanar; síntesis de la microstrip (W/h, εeff).",
              "Discontinuidades, sustratos y conectores.",
              "Resumen: fórmulas de análisis y de síntesis de la microstrip."] },
    { id: "ciaf-p04", s: "CIAF", ph: "P", m: 90, t: "Carta de Smith",
      f: ["cSmith", "cCartas"],
      steps: ["Cómo se construye la carta y cómo se usa como calculadora de líneas (Z ↔ Y, desplazamiento por la línea).",
              "Imprime cartas en blanco del zip y practica a lápiz."] },
    { id: "ciaf-p05", s: "CIAF", ph: "P", m: 90, t: "Adaptación de impedancias",
      f: ["cSmith", "cT2zip"],
      steps: ["Stub simple, transformador λ/4 y redes en L.",
              "Rehaz los ejemplos de las transparencias (zip)."] },
    { id: "ciaf-p06", s: "CIAF", ph: "P", m: 90, t: "Problemas de carta de Smith y adaptación",
      f: ["cT2e", "cT2s"],
      steps: ["Haz los enunciados a lápiz sobre la carta y corrige con las soluciones."] },
    { id: "ciaf-p07", s: "CIAF", ph: "P", m: 90, t: "Parámetros Z, Y, S y ABCD",
      f: ["cS"],
      steps: ["Definiciones, propiedades (reciprocidad, pérdidas, simetría) y conversión entre ellos.",
              "Resumen: tabla de conversiones y propiedades de [S]."] },
    { id: "ciaf-p08", s: "CIAF", ph: "P", m: 90, t: "Problemas de parámetros S",
      f: ["cT3e", "cT3s"],
      steps: ["Haz los enunciados de parámetros S y corrige."] },
    { id: "ciaf-p09", s: "CIAF", ph: "P", m: 60, t: "Redes de dos puertos y atenuadores",
      f: ["cQucs", "cS"],
      steps: ["Γin y Γout, ganancias de potencia, return loss e insertion loss.",
              "Atenuadores en QUCS circuits (primeras diapositivas)."] },
    { id: "ciaf-p10", s: "CIAF", ph: "P", m: 60, t: "Práctica con QUCS",
      f: ["cMsQ"],
      steps: ["Instala QUCS-S y simula una línea microstrip y una red de adaptación.",
              "Te sirve para las prácticas (25 %)."] },
    { id: "ciaf-p11", s: "CIAF", ph: "P", m: 45, t: "Formulario para el parcial",
      f: ["cForm"],
      steps: ["Parte del Formulario y haz una ficha en papel con lo que entra en el parcial."] },
    { id: "ciaf-p12", s: "CIAF", ph: "P", m: 120, t: "Simulacro: problemas de LT, Smith y S",
      f: ["cEx24", "cEx24s"],
      steps: ["Haz los problemas de LT, Smith y parámetros S del examen 18/01/24 cronometrado.",
              "Corrige con la solución."] },
    { id: "ciaf-p13", s: "CIAF", ph: "P", m: 60, t: "Repaso de errores",
      f: ["cT2e", "cT3e"],
      steps: ["Rehaz los problemas que fallaste."] },

    // ───────────── CIAF · final 18/1 ─────────────
    { id: "ciaf-f01", s: "CIAF", ph: "F", m: 75, t: "Divisores: resistivo y Wilkinson",
      f: ["cQucs"],
      steps: ["Propiedades de las redes de 3 puertos, divisor resistivo y Wilkinson.",
              "Resumen: matriz S de cada uno y en qué se diferencian."] },
    { id: "ciaf-f02", s: "CIAF", ph: "F", m: 75, t: "Circuladores e híbridos de 90° y 180°",
      f: ["cQucs"],
      steps: ["Matriz S, funcionamiento y aplicaciones.",
              "Resumen: dibujo y matriz S de cada uno."] },
    { id: "ciaf-f03", s: "CIAF", ph: "F", m: 90, t: "Líneas acopladas y acoplador direccional",
      f: ["cAcop", "cQucs"],
      steps: ["Análisis en modo par e impar, acoplamiento, directividad y aislamiento.",
              "Resumen: fórmulas de diseño del acoplador."] },
    { id: "ciaf-f04", s: "CIAF", ph: "F", m: 75, t: "Filtros de microondas",
      f: [],
      steps: ["Necesitas la teoría de filtros de Atenea (ver Material).",
              "Prototipos, transformaciones e implementación con líneas."] },
    { id: "ciaf-f05", s: "CIAF", ph: "F", m: 90, t: "Problemas de circuitos pasivos",
      f: ["cEx24", "cM17", "cM16"],
      steps: ["Haz los problemas de divisores, híbridos y acopladores de los exámenes."] },
    { id: "ciaf-f06", s: "CIAF", ph: "F", m: 75, t: "Ruido y margen dinámico",
      f: [],
      steps: ["Temperatura equivalente, figura de ruido y fórmula de Friis (transparencias de Atenea).",
              "Resumen: Friis con un ejemplo de cadena receptora."] },
    { id: "ciaf-f07", s: "CIAF", ph: "F", m: 60, t: "Detectores y mezcladores",
      f: [],
      steps: ["Diodo detector, mezcladores, pérdidas de conversión y frecuencia imagen (Atenea)."] },
    { id: "ciaf-f08", s: "CIAF", ph: "F", m: 90, t: "Amplificadores de microondas: ganancia y estabilidad",
      f: ["cAmp", "cT4t"],
      steps: ["Transistores de microondas, ganancias (GT, GA, GP), estabilidad (K-Δ, μ) y círculos de estabilidad.",
              "Resumen: fórmulas de ganancia y de estabilidad."] },
    { id: "ciaf-f09", s: "CIAF", ph: "F", m: 90, t: "Diseño de amplificadores",
      f: ["cAmp", "cT4t"],
      steps: ["Máxima ganancia (adaptación conjugada), diseño unilateral, círculos de ganancia constante y círculos de ruido.",
              "Revisa el ejemplo del LNA para DBS."] },
    { id: "ciaf-f10", s: "CIAF", ph: "F", m: 120, t: "Problemas de amplificadores",
      f: ["cT4e", "cT4s"],
      steps: ["Haz los enunciados y corrige con los resueltos."] },
    { id: "ciaf-f11", s: "CIAF", ph: "F", m: 90, t: "Osciladores",
      f: ["cOsc"],
      steps: ["Osciladores de resistencia negativa y con transistor (busca la teoría en Atenea).",
              "Haz los problemas de osciladores."] },
    { id: "ciaf-f12", s: "CIAF", ph: "F", m: 60, t: "MMIC, circuitos híbridos e instrumentos",
      f: [],
      steps: ["MMIC frente a HMIC; analizador de espectro, VNA y medidor de figura de ruido (Atenea).",
              "Resumen: una ficha con características, limitaciones y calibración."] },
    { id: "ciaf-f13", s: "CIAF", ph: "F", m: 180, t: "Simulacro: examen CIAF 18/01/24",
      f: ["cEx24", "cEx24s"],
      steps: ["Hazlo entero en 3 h y corrígelo."] },
    { id: "ciaf-f14", s: "CIAF", ph: "F", m: 150, t: "Simulacro: MICROS 2017-18",
      f: ["cM17"],
      steps: ["Haz los problemas cronometrado. Se salta lo que no entra en CIAF."] },
    { id: "ciaf-f15", s: "CIAF", ph: "F", m: 150, t: "Simulacro: MICROS 2016-17",
      f: ["cM16"],
      steps: ["Haz los problemas cronometrado y corrígelo."] },
    { id: "ciaf-f16", s: "CIAF", ph: "F", m: 75, t: "Formulario final y repaso",
      f: ["cForm"],
      steps: ["Formulario en limpio y lista de errores típicos."] }
  ];

  // Material que falta según la guía docente y lo que hay en Drive
  const GAPS = [
    { id: "g-dmic-1", s: "DMIC", t: "Transparencias del tema de circuitos digitales CMOS (característica DC, retardo, consumo, buffers, restricciones temporales)" },
    { id: "g-dmic-2", s: "DMIC", t: "Transparencias de análisis DC del MOS y de pequeña señal (si están separadas de MOS Equations)" },
    { id: "g-dmic-3", s: "DMIC", t: "Transparencias de circuitos analógicos: CS/CD/CG, cascode, espejos, cargas activas, respuesta en frecuencia y diferenciales" },
    { id: "g-dmic-4", s: "DMIC", t: "Transparencias de RF: LNA, ruido y no linealidad" },
    { id: "g-dmic-5", s: "DMIC", t: "Enunciados y fechas de los «Exercicis per lliurar» de este curso (cuentan en la AC)" },
    { id: "g-dmic-6", s: "DMIC", t: "Parciales de cursos anteriores con solución (solo tienes finales)" },
    { id: "g-dmic-7", s: "DMIC", t: "Guiones de laboratorio QT26 (tienes versiones Q24/Q25) y tu grupo de lab para las fechas de los controles" },
    { id: "g-hips-1", s: "HIPS", t: "Chapter 4: Adaptive filters y Learning mechanisms (transparencias)" },
    { id: "g-hips-2", s: "HIPS", t: "Ejercicios del Chapter 1 y del Chapter 4, si existen" },
    { id: "g-hips-3", s: "HIPS", t: "Parciales (controls) de otros años además del 25 T" },
    { id: "g-hips-4", s: "HIPS", t: "Versión 2026 de las transparencias (las tuyas son del curso 25-26) y guiones de los labs 3–8" },
    { id: "g-ciaf-1", s: "CIAF", t: "Teoría de circuitos pasivos: atenuadores, filtros, divisores e híbridos (solo tienes las diapositivas de QUCS)" },
    { id: "g-ciaf-2", s: "CIAF", t: "Ruido y margen dinámico (Friis), detectores y mezcladores" },
    { id: "g-ciaf-3", s: "CIAF", t: "Teoría de osciladores (solo tienes los problemas)" },
    { id: "g-ciaf-4", s: "CIAF", t: "Circuitos híbridos y MMIC; instrumentos de microondas (analizador de espectro, VNA, medidor de NF)" },
    { id: "g-ciaf-5", s: "CIAF", t: "Exámenes finales 2025 y 2026 y controles anteriores (solo tienes el del 18/01/24)" },
    { id: "g-ciaf-6", s: "CIAF", t: "Material de prácticas de ordenador y laboratorio de este curso (25 %, obligatorias)" },
    { id: "g-ciaf-7", s: "CIAF", t: "Fechas de los controles de este curso además del parcial del 5/11" }
  ];

  return { START, AFTER_MIDTERMS, SUBJECTS, EXAMS, MILESTONES, HOLIDAYS, FILES, TASKS, GAPS };
})();
